### ISSUE TITLE
installation issue for dssp

### ISSUE THREAD

**Issue by charlieccp** [mhekkel/libmcfp#2]
Hi,

I'm trying to install DSSP so, as indicated here https://github.com/PDB-REDO/dssp, I need libmcfp to do so.

However in the last step of the installation (cmake --install .) I have the following error:
-- Install configuration: ""
-- Installing: /usr/local/include/mcfp.hpp
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot copy file
  "/home/charlieccp/libmcfp/include/mcfp/mcfp.hpp" to
  "/usr/local/include/mcfp.hpp": Permission denied.
  
  Note that all other steps worked without any problem.

Could you please advice me on what to do now?

I'm using ubuntu on windows.

Thanks for your time.

Best wishes,
Charlotte

**Comment by mhekkel** [comment]
In the config step of libmcfp, specify:

-DCMAKE_INSTALL_PREFIX=$HOME/.local

Similar to to what is specified in the [libcifpp](https://github.com/PDB-REDO/libcifpp) readme.
